/*
IONOS Cloud - DNS API

Cloud DNS service helps IONOS Cloud customers to automate DNS Zone and Record management.

API version: 1.17.0
Contact: support@cloud.ionos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
)

// checks if the ErrorMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorMessagesInner{}

// ErrorMessagesInner struct for ErrorMessagesInner
type ErrorMessagesInner struct {
	// Internal error code.
	ErrorCode *string `json:"errorCode,omitempty"`
	// Human readable explanation of the issue.
	Message *string `json:"message,omitempty"`
}

// NewErrorMessagesInner instantiates a new ErrorMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorMessagesInner() *ErrorMessagesInner {
	this := ErrorMessagesInner{}
	return &this
}

// NewErrorMessagesInnerWithDefaults instantiates a new ErrorMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorMessagesInnerWithDefaults() *ErrorMessagesInner {
	this := ErrorMessagesInner{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *ErrorMessagesInner) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorMessagesInner) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *ErrorMessagesInner) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *ErrorMessagesInner) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrorMessagesInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorMessagesInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrorMessagesInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ErrorMessagesInner) SetMessage(v string) {
	o.Message = &v
}

func (o ErrorMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableErrorMessagesInner struct {
	value *ErrorMessagesInner
	isSet bool
}

func (v NullableErrorMessagesInner) Get() *ErrorMessagesInner {
	return v.value
}

func (v *NullableErrorMessagesInner) Set(val *ErrorMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorMessagesInner(val *ErrorMessagesInner) *NullableErrorMessagesInner {
	return &NullableErrorMessagesInner{value: val, isSet: true}
}

func (v NullableErrorMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
