/*
IONOS Cloud - DNS API

Cloud DNS service helps IONOS Cloud customers to automate DNS Zone and Record management.

API version: 1.17.0
Contact: support@cloud.ionos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecordEnsure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordEnsure{}

// RecordEnsure struct for RecordEnsure
type RecordEnsure struct {
	Properties Record `json:"properties"`
}

type _RecordEnsure RecordEnsure

// NewRecordEnsure instantiates a new RecordEnsure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordEnsure(properties Record) *RecordEnsure {
	this := RecordEnsure{}
	this.Properties = properties
	return &this
}

// NewRecordEnsureWithDefaults instantiates a new RecordEnsure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordEnsureWithDefaults() *RecordEnsure {
	this := RecordEnsure{}
	return &this
}

// GetProperties returns the Properties field value
func (o *RecordEnsure) GetProperties() Record {
	if o == nil {
		var ret Record
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *RecordEnsure) GetPropertiesOk() (*Record, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *RecordEnsure) SetProperties(v Record) {
	o.Properties = v
}

func (o RecordEnsure) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordEnsure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *RecordEnsure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordEnsure := _RecordEnsure{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordEnsure)

	if err != nil {
		return err
	}

	*o = RecordEnsure(varRecordEnsure)

	return err
}

type NullableRecordEnsure struct {
	value *RecordEnsure
	isSet bool
}

func (v NullableRecordEnsure) Get() *RecordEnsure {
	return v.value
}

func (v *NullableRecordEnsure) Set(val *RecordEnsure) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordEnsure) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordEnsure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordEnsure(val *RecordEnsure) *NullableRecordEnsure {
	return &NullableRecordEnsure{value: val, isSet: true}
}

func (v NullableRecordEnsure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordEnsure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
