# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.ionos.com

certManager: 
  serviceAccountName: cert-manager
  namespace: cert-manager

replicaCount: 1

## Additional container environment variables
##
## You specify this manually like you would a raw deployment manifest.
## This means you can bind in environment variables from secrets.
##
## e.g. static environment variables:
##  - name: HTTP_PROXY
##    value: "http://proxy.example.com:8080"
##  - name: HTTPS_PROXY
##    value: "http://proxy.example.com:8080"
##  - name: NO_PROXY
##    value: "localhost,127.0.0.1,.svc"
## e.g. secret environment variable:
## - name: USERNAME
##   valueFrom:
##     secretKeyRef:
##       name: mysecret
##       key: username
env: []

image:
  tag: latest
  repository: ghcr.io/ionos-cloud/cert-manager-webhook-ionos-cloud
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}