apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-ionos-e2e
spec:
  acme:
    # using zerossl because let's encrypt has rate limiting issues
    server: https://acme.zerossl.com/v2/DV90
    email: paas-dns@ionos.com
    privateKeySecretRef:
      name: letsencrypt-ionos
    solvers:
    - dns01:
        webhook:
          solverName: ionos-cloud
          groupName: acme.ionos.com
