apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-ionos-e2e
spec:
  acme:
    # using let's encrypt staging to avoid any rate limiting issues
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: paas-dns@ionos.com
    privateKeySecretRef:
      name: letsencrypt-ionos
    solvers:
    - dns01:
        webhook:
          solverName: ionos-cloud
          groupName: acme.ionos.com
