apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-ionos-cloud.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-webhook-ionos-cloud.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "cert-manager-webhook-ionos-cloud.name" . }}