name: deploy helm chart
on:
    workflow_dispatch:


jobs:
    deploy:
        name: deploy helm chart
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v5
              with:
                fetch-depth: 0
            - name: Fetch latest tag
              id: get-latest-tag
              run: |
                git fetch --tags
                echo "latest-tag=$(git tag --list --sort='-*authordate' | tail -n 1)" >> "$GITHUB_OUTPUT"
            - name: Install helm chart
              uses: azure/setup-helm@v4.3.1
            - name: Package helm chart
              run: |
                helm package chart/cert-manager-webhook-ionos-cloud/ --app-version ${{ steps.get-latest-tag.outputs.latest-tag }}
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                tag: chart-${{ steps.get-latest-tag.outputs.latest-tag }}
                name: chart-${{ steps.get-latest-tag.outputs.latest-tag }}
                body: | 
                    Helm chart version ${{ steps.get-latest-tag.outputs.latest-tag }}
                token: ${{ github.token }}
                prerelease: false
                makeLatest: false
                allowUpdates: true
                artifacts: >
                  *.tgz
            - name: switch to helm repo branch and create/update index.yaml
              run: |
                git checkout helm-repo
                helm repo index . --merge index.yaml \
                --url https://github.com/ionos-cloud/cert-manager-webhook-ionos-cloud/releases/download/chart-${{ steps.get-latest-tag.outputs.latest-tag }}/
                git config user.email "no-reply@ionos-cloud.com";
                git config user.name "IONOS-CloudBot";
                git add index.yaml
                git commit -m "chore(chart): update helm repository index"
                git push origin helm-repo
    

            

            

            