name: deploy helm chart
on:
    workflow_dispatch:


jobs:
    deploy:
        name: deploy helm chart
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Fetch latest tag
              id: get-latest-tag
              run: |
                git fetch --tags
                echo "latest-tag=$(git tag --list --sort='-*authordate' | head -n 1)" >> "$GITHUB_OUTPUT"
            - name: Install helm chart
              uses: azure/setup-helm@v4.3.0
            - name: Package helm chart
              run: |
                helm package chart/cert-manager-webhook-ionos-cloud/
                ls
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                name: ${{ steps.get-latest-tag.outputs.latest-tag }} - Chart
                body: | 
                    Helm chart version ${{ steps.get-latest-tag.outputs.latest-tag }}
                token: ${{ github.token }}
                prerelease: false
                makeLatest: true
                artifacts: >
                  *.tgz
            - name: switch to helm repo branch and create/update index.yaml
              run: |
                git checkout helm-repo
                # if index.yaml exists and is not empty, we use merge
                if [ -a index.yaml ] && [ -s index.yaml ]; then
                  helm repo index . --merge index.yaml --url https://github.com/ionos-cloud/cert-manager-webhook-ionos-cloud/releases/download/
                else
                  helm repo index . --url https://github.com/ionos-cloud/cert-manager-webhook-ionos-cloud/releases/download/
                fi

                git config user.email "no-reply@ionos-cloud.com";
                git config user.name "IONOS-CloudBot";
                git add index.yaml
                git commit -m "chore(chart): update helm repository index"
                git push origin helm-repo
    

            

            

            